# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================
# Workflow-specific settings for CRE CLI targets.
# Each target defines user-workflow and workflow-artifacts groups.
# Settings here override CRE Project Settings File values.

staging-settings:
  user-workflow:
    workflow-name: "polymarket-open-markets"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

production-settings:
  user-workflow:
    workflow-name: "polymarket-open-markets"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
